#!/usr/bin/env python3
"""Create a same-manuscript Word reference while preserving template formatting."""

from __future__ import annotations

import argparse
import copy
import json
import shutil
import subprocess
import tempfile
import zipfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Inches


TITLE = "Temp2TeX Regression Benchmark: Template Fidelity Across Journal Formats"
ABSTRACT = (
    "This benchmark manuscript is intentionally structured to exercise journal template behavior. "
    "It contains front matter, author notes, an abstract, keywords, multiple heading levels, equations, "
    "tables, figures, footnotes, references, declarations, and an appendix. The same body is rendered "
    "through the official Word template and the LaTeX package generated by Temp2TeX from the official Word template."
)
KEYWORDS = "template conversion; LaTeX; Word template; regression testing; journal formatting"
SECTIONS = [
    (
        "Introduction",
        "The regression body verifies whether a converted template preserves the visual contract that a journal author expects from the official source. The body includes paragraphs with citations, inline mathematical symbols, emphasized terms, and cross references. A short footnote appears here to check footnote placement and numbering.",
    ),
    (
        "Methods",
        "The method section includes an equation and explanatory text. Equation (1) should appear with the journal's equation spacing and numbering policy.",
    ),
    (
        "Tables and Figures",
        "Table 1 checks caption placement, table rules, notes, alignment, and merged-cell behavior.",
    ),
    (
        "Results",
        "The result text cites the regression table, the single-panel figure, the paired-panel figure, and the displayed equation. The paragraph is long enough to wrap across multiple lines so the comparison can observe line spacing and text block width. It also contains a parenthetical citation placeholder (Author et al., 2026).",
    ),
    (
        "Discussion",
        "Discussion text checks body spacing after floats and headings. The converted template should keep the same page frame, header and footer behavior, caption style, and reference placement as the official LaTeX template when both templates receive this same manuscript body.",
    ),
    (
        "Conclusion",
        "This fixed body is not a scientific article. It is a deterministic template stress test for regression comparison.",
    ),
]

SECOND_LEVEL_TEXT = (
    "This section checks heading hierarchy, vertical spacing, paragraph indentation, and line width. "
    "It also verifies that a journal template can render normal body text without relying on example-specific macros."
)
THIRD_LEVEL_TEXT = (
    "Third-level headings are included because many official Word templates define them even when their LaTeX templates use a different command style."
)
RESULTS_TEXT = (
    "The result text cites Table 1, Figure 1, Figure 2, and Equation 1. The paragraph is long enough to wrap across multiple lines so that the comparison can observe line spacing and text block width. It also includes a parenthetical citation placeholder in plain text (Author et al., 2026)."
)
EQUATION_TEXT = "I = (sum from i=1 to n of w_i x_i) / (sum from i=1 to n of w_i)"


def normalize_name(value: str) -> str:
    return " ".join(value.lower().replace("_", " ").replace("-", " ").split())


def paragraph_styles(doc: Document) -> list:
    return [style for style in doc.styles if style.type == WD_STYLE_TYPE.PARAGRAPH]


def style_by_terms(
    doc: Document,
    terms: list[str],
    excluded: tuple[str, ...] = (),
    prefer_used: bool = True,
):
    scored = []
    usage = style_usage(doc) if prefer_used else Counter()
    for style in paragraph_styles(doc):
        name = normalize_name(style.name)
        if any(term in name for term in excluded):
            continue
        score = 0
        for index, term in enumerate(terms):
            if name == term:
                score = max(score, 9000 - index * 1000)
            elif term in name:
                score = max(score, 8000 - index * 1000)
        if score:
            scored.append((score, bool(usage[style.style_id]), style))
    if prefer_used and any(item[1] for item in scored):
        scored = [item for item in scored if item[1]]
    return max(scored, key=lambda item: item[0])[2] if scored else None


def style_from_text(doc: Document, prefixes: tuple[str, ...]):
    for paragraph in doc.paragraphs:
        text = paragraph.text.strip().lower()
        if text.startswith(prefixes) and paragraph.style:
            return paragraph.style
    return None


def infer_body_style(doc: Document, excluded_ids: set[str]):
    counts: Counter[str] = Counter()
    styles = {}
    for paragraph in doc.paragraphs:
        text = paragraph.text.strip()
        style = paragraph.style
        if len(text) < 80 or not style or style.style_id in excluded_ids:
            continue
        # Template instructions often contain many long bibliography entries.
        # Exclude semantic non-body styles before choosing the most common
        # paragraph style, otherwise the regression manuscript is normalized
        # with a reference or caption style instead of the article body style.
        name = normalize_name(style.name)
        if any(term in name for term in (
            "reference", "bibliograph", "bib entry", "bibentry", "citation",
            "caption", "footnote", "endnote", "list", "table", "figure",
            "algorithm", "header", "footer", "acknowledg", "author", "affiliation",
            "abstract", "keyword", "title", "heading", "head ", "appendix",
        )):
            continue
        counts[style.style_id] += 1
        styles[style.style_id] = style
    if counts:
        return styles[counts.most_common(1)[0][0]]
    return style_by_terms(doc, ["body text", "body", "normal"])


def style_usage(doc: Document) -> Counter[str]:
    return Counter(
        paragraph.style.style_id
        for paragraph in doc.paragraphs
        if paragraph.text.strip() and paragraph.style is not None
    )


def infer_styles(doc: Document) -> dict[str, object]:
    title = style_by_terms(doc, ["article title", "manuscript title", "title"], ("subtitle", "running"))
    author = style_by_terms(doc, ["authors", "author"])
    affiliation = style_by_terms(doc, ["affiliations", "affiliation", "address", "institution"])
    abstract = style_by_terms(doc, ["abstract"]) or style_from_text(doc, ("abstract",))
    keywords = style_by_terms(doc, ["keywords", "key words"]) or style_from_text(doc, ("keywords", "key words"))
    heading1 = style_by_terms(doc, ["heading 1", "heading1", "head 1", "head1", "section heading", "main text", "section"], ("reference", "supporting"))
    heading2 = style_by_terms(doc, ["heading 2", "heading2", "head 2", "head2", "subsection"])
    heading3 = style_by_terms(doc, ["heading 3", "heading3", "head 3", "head3", "subsubsection"])
    caption = style_by_terms(doc, ["figure caption", "table caption", "caption"])
    reference = style_by_terms(doc, ["reference item", "references", "bibliography", "bib entry", "bibentry"])
    footnote = style_by_terms(doc, ["footnote text", "footnote"])
    excluded = {
        style.style_id
        for style in (title, author, affiliation, abstract, keywords, heading1, heading2, heading3, caption, reference)
        if style is not None
    }
    normal = style_by_terms(doc, ["normal"]) or next(iter(paragraph_styles(doc)), None)
    usage = style_usage(doc)
    named_body = style_by_terms(doc, ["main text", "body text", "article body", "journal body"])
    body = named_body if named_body is not None and usage[named_body.style_id] else infer_body_style(doc, excluded)
    if body is not None and normalize_name(body.name) in {"list", "list paragraph"}:
        body = normal
    roles = {
        "title": title or normal,
        "author": author or normal,
        "affiliation": affiliation or author or normal,
        "abstract": abstract or body or normal,
        "keywords": keywords or abstract or body or normal,
        "heading1": heading1 or normal,
        "heading2": heading2 or heading1 or normal,
        "heading3": heading3 or heading2 or heading1 or normal,
        "body": body or normal,
        "caption": caption or body or normal,
        "reference": reference or body or normal,
        "footnote": footnote or body or normal,
    }
    return roles


def find_soffice() -> str | None:
    candidates = [
        shutil.which("soffice"),
        shutil.which("soffice.exe"),
        r"D:\LibreOffice\program\soffice.exe",
    ]
    return next((item for item in candidates if item and Path(item).exists()), None)


def is_plain_docx_document(source: Path) -> bool:
    """Only bypass conversion for a package python-docx can open as a document."""
    if source.suffix.lower() != ".docx" or not zipfile.is_zipfile(source):
        return False
    try:
        with zipfile.ZipFile(source) as archive:
            content_types = archive.read("[Content_Types].xml")
        return b"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml" in content_types
    except (KeyError, OSError, zipfile.BadZipFile):
        return False


def convert_to_docx(source: Path, workdir: Path) -> tuple[Path | None, dict]:
    if is_plain_docx_document(source):
        return source, {"needed": False, "success": True, "source": str(source)}
    soffice = find_soffice()
    report = {"needed": True, "success": False, "source": str(source), "soffice": soffice}
    if not soffice:
        report["error"] = "LibreOffice is required to normalize legacy DOC/DOT/RTF or DOTX input"
        return None, report
    proc = subprocess.run(
        [soffice, "--headless", "--convert-to", "docx", "--outdir", str(workdir), str(source)],
        text=True,
        capture_output=True,
        timeout=45,
    )
    candidates = sorted(workdir.glob("*.docx"), key=lambda path: path.stat().st_mtime, reverse=True)
    report.update(
        {
            "returncode": proc.returncode,
            "stdout_tail": proc.stdout[-2000:],
            "stderr_tail": proc.stderr[-2000:],
            "success": bool(proc.returncode == 0 and candidates),
        }
    )
    if not report["success"]:
        report["error"] = "LibreOffice did not produce a DOCX normalization source"
        return None, report
    report["converted_docx"] = str(candidates[0])
    return candidates[0], report


def clear_body(doc: Document) -> None:
    body = doc._element.body
    for child in list(body):
        if child.tag.endswith("}sectPr"):
            continue
        body.remove(child)


def materialize_inherited_page_furniture(doc: Document) -> dict:
    """Make the final section's inherited header/footer references explicit."""
    sections = list(doc._element.body.xpath(".//w:sectPr"))
    if not sections:
        return {"section_count": 0, "materialized": []}

    active: dict[tuple[str, str], object] = {}
    for section in sections:
        for kind in ("headerReference", "footerReference"):
            for reference in section.findall(qn(f"w:{kind}")):
                variant = reference.get(qn("w:type")) or "default"
                active[(kind, variant)] = reference

    final_section = sections[-1]
    explicit = {
        (kind, reference.get(qn("w:type")) or "default")
        for kind in ("headerReference", "footerReference")
        for reference in final_section.findall(qn(f"w:{kind}"))
    }
    materialized = []
    for (kind, variant), reference in active.items():
        if (kind, variant) in explicit:
            continue
        copied = copy.deepcopy(reference)
        # Header/footer references must precede the page geometry children in
        # sectPr. Insert after any existing reference nodes.
        insert_at = 0
        for index, child in enumerate(final_section):
            local = child.tag.split("}")[-1]
            if local in {"headerReference", "footerReference"}:
                insert_at = index + 1
        final_section.insert(insert_at, copied)
        materialized.append(
            {
                "kind": "header" if kind == "headerReference" else "footer",
                "variant": variant,
                "relationship_id": copied.get(qn("r:id")),
                "source": "inherited from the latest preceding Word section reference",
            }
        )
    return {"section_count": len(sections), "materialized": materialized}


def front_matter_column_transition(doc: Document) -> dict:
    """Capture an explicit continuous one-column to two-column transition."""
    sections = list(doc._element.body.xpath(".//w:sectPr"))

    def column_count(section) -> int:
        columns = section.find(qn("w:cols"))
        if columns is None:
            return 1
        try:
            return max(1, int(columns.get(qn("w:num")) or "1"))
        except ValueError:
            return 1

    for index in range(len(sections) - 1):
        current = sections[index]
        following = sections[index + 1]
        break_node = current.find(qn("w:type"))
        break_type = break_node.get(qn("w:val")) if break_node is not None else "nextPage"
        if column_count(current) == 1 and column_count(following) == 2 and break_type == "continuous":
            return {
                "available": True,
                "source_section_index": index + 1,
                "following_section_index": index + 2,
                "break_type": break_type,
                "from_columns": 1,
                "to_columns": 2,
                "sectPr": copy.deepcopy(current),
            }
    return {"available": False}


def attach_section_break(paragraph, transition: dict) -> bool:
    section = transition.get("sectPr") if isinstance(transition, dict) else None
    if section is None:
        return False
    properties = paragraph._p.get_or_add_pPr()
    existing = properties.find(qn("w:sectPr"))
    if existing is not None:
        properties.remove(existing)
    properties.append(copy.deepcopy(section))
    return True


def copy_direct_paragraph_format(source, target) -> None:
    """Copy paragraph and baseline run properties from a direct-format source."""
    if source is None:
        return
    source_ppr = source._p.pPr
    if source_ppr is not None:
        target_ppr = target._p.pPr
        if target_ppr is not None:
            target._p.remove(target_ppr)
        target._p.insert(0, copy.deepcopy(source_ppr))
    if source.runs and target.runs and source.runs[0]._r.rPr is not None:
        target_run = target.runs[0]
        target_rpr = target_run._r.rPr
        if target_rpr is not None:
            target_run._r.remove(target_rpr)
        target_run._r.insert(0, copy.deepcopy(source.runs[0]._r.rPr))


def add_paragraph(doc: Document, text: str, style, source=None) -> object:
    paragraph = doc.add_paragraph(style=style)
    paragraph.add_run(text)
    copy_direct_paragraph_format(source, paragraph)
    return paragraph


def direct_role_samples(doc: Document) -> dict[str, object]:
    """Find visible role exemplars for templates that do not use Word styles."""
    paragraphs = [paragraph for paragraph in doc.paragraphs if paragraph.text.strip()]

    def first(predicate):
        return next((paragraph for index, paragraph in enumerate(paragraphs, 1) if predicate(paragraph.text.strip(), index)), None)

    affiliation_markers = ("university", "college", "institute", "laboratory", "department", "\u5927\u5b66", "\u5b66\u9662", "\u7814\u7a76\u6240", "\u5b9e\u9a8c\u5ba4", "\u5355\u4f4d", "\u90ae\u7f16")
    def is_affiliation(text: str) -> bool:
        return any(marker in text.lower() for marker in affiliation_markers)
    def heading_level(text: str):
        import re
        match = re.match(r"^(\d+)(?:\.(\d+))?(?:\.(\d+))?[.)]?\s+\S+", text)
        if not match or is_affiliation(text):
            return None
        return 2 if match.group(3) else 1 if match.group(2) else 0

    title = first(lambda text, index: index <= 3 and len(text) >= 6)
    abstract = first(lambda text, index: text.lower().startswith("abstract") or text.startswith("\u6458\u8981"))
    keywords = first(lambda text, index: text.lower().startswith(("keyword", "key word")) or text.startswith("\u5173\u952e\u8bcd"))
    author = first(lambda text, index: index <= 8 and ("," in text or "\uff0c" in text) and not text.startswith(("\u6458\u8981", "\u5173\u952e\u8bcd")))
    affiliation = first(lambda text, index: index <= 16 and is_affiliation(text))
    body = max((paragraph for paragraph in paragraphs if len(paragraph.text.strip()) >= 80), key=lambda item: len(item.text), default=None)
    headings = {level: first(lambda text, index, level=level: heading_level(text) == level) for level in range(3)}
    reference = first(lambda text, index: text.lower() == "references" or text.startswith("\u53c2\u8003\u6587\u732e"))
    return {
        "title": title,
        "author": author,
        "affiliation": affiliation,
        "abstract": abstract,
        "keywords": keywords,
        "heading1": headings[0],
        "heading2": headings[1] or headings[0],
        "heading3": headings[2] or headings[1] or headings[0],
        "body": body,
        "caption": body,
        "reference": reference or body,
        "footnote": body,
    }


def add_placeholder_figure(doc: Document, path: Path, style, *, paired: bool = False) -> None:
    try:
        from PIL import Image, ImageDraw

        path.parent.mkdir(parents=True, exist_ok=True)
        image = Image.new("RGB", (1200, 480), "white")
        draw = ImageDraw.Draw(image)
        if paired:
            draw.rectangle((8, 8, 571, 471), outline="black", width=6)
            draw.rectangle((629, 8, 1191, 471), outline="black", width=6)
            draw.text((175, 210), "Panel A", fill="black")
            draw.text((795, 210), "Panel B", fill="black")
        else:
            draw.rectangle((8, 8, 1191, 471), outline="black", width=6)
            draw.text((70, 210), "Temp2TeX regression figure placeholder", fill="black")
        image.save(path)
        paragraph = doc.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        paragraph.add_run().add_picture(str(path), width=Inches(4.7))
    except Exception:
        add_paragraph(doc, "[Temp2TeX regression figure placeholder]", style)
    caption = "Two-panel figure placeholder used for subfigure regression" if paired else "Single-panel figure placeholder used for layout regression"
    add_paragraph(doc, f"Figure {'2' if paired else '1'}. {caption}", style)


def build_normalized_document(source_docx: Path, output: Path, figure_path: Path) -> dict:
    doc = Document(str(source_docx))
    original_section_count = len(doc.sections)
    inherited_page_furniture = materialize_inherited_page_furniture(doc)
    column_transition = front_matter_column_transition(doc)
    original_table_style = None
    if doc.tables and doc.tables[0].style:
        original_table_style = doc.tables[0].style.name
    styles = infer_styles(doc)
    style_names = {role: style.name if style is not None else None for role, style in styles.items()}
    direct_sources = direct_role_samples(doc)
    clear_body(doc)
    direct_copy_decisions: dict[str, str] = {}

    def add_role(role: str, text: str):
        source = direct_sources.get(role)
        target_style = styles[role]
        # Direct formatting may only be copied from the same Word style. A
        # long Abstract/instruction paragraph must not overwrite body text.
        if source is not None and target_style is not None and source.style is not None:
            if source.style.style_id != target_style.style_id:
                direct_copy_decisions[role] = "skipped_style_mismatch"
                source = None
            else:
                direct_copy_decisions[role] = "copied_same_style"
        elif source is not None:
            direct_copy_decisions[role] = "copied_no_style_guard"
        return add_paragraph(doc, text, target_style, source)

    add_role("title", TITLE)
    add_role("author", "Alex Example and Blair Example")
    affiliation_paragraph = add_role("affiliation", "Department of Template Engineering, Example University; alex.example@example.org")
    transition_attached = attach_section_break(affiliation_paragraph, column_transition)
    add_role("abstract", f"Abstract: {ABSTRACT}")
    add_role("keywords", f"Keywords: {KEYWORDS}")

    for heading, text in SECTIONS:
        add_role("heading1", heading)
        paragraph = add_role("body", text)
        if heading == "Introduction":
            marker = paragraph.add_run("1")
            marker.font.superscript = True
            add_role("footnote", "1 This footnote is part of the fixed regression body.")
        if heading == "Introduction":
            add_role("heading2", "Second-level heading")
            add_role("body", SECOND_LEVEL_TEXT)
            add_role("heading3", "Third-level heading")
            add_role("body", THIRD_LEVEL_TEXT)
        if heading == "Tables and Figures":
            add_role("caption", "Table 1. Regression table with a note and a merged cell")
            table = doc.add_table(rows=4, cols=3)
            if original_table_style:
                try:
                    table.style = original_table_style
                except Exception:
                    pass
            values = [
                ("Format element", "Expected stress", "Evidence target"),
                ("Merged-cell row", "", "table structure"),
                ("Heading levels", "section to subsubsection", "text hierarchy"),
                ("Figures", "single and paired panels", "caption layout"),
            ]
            for row, values_row in zip(table.rows, values):
                for cell, value in zip(row.cells, values_row):
                    cell.text = value
            add_role("caption", "Note: the table intentionally includes a note below the tabular block.")
            add_placeholder_figure(doc, figure_path, styles["caption"])
            add_placeholder_figure(doc, figure_path.with_name("paired-figure-placeholder.png"), styles["caption"], paired=True)
        if heading == "Methods":
            add_role("body", EQUATION_TEXT)
        if heading == "Results":
            # Replace the generic section text with the same content ordering
            # used by the LaTeX stress body.
            paragraph.text = RESULTS_TEXT
            paragraph.style = styles["body"]

    add_role("heading1", "Acknowledgements")
    add_role("body", "The authors thank the template maintainers. No external funding was used.")
    add_role("heading1", "Data Availability")
    add_role("body", "All data in this manuscript are placeholders created for template regression testing.")
    add_role("heading1", "References")
    add_role("reference", "Author A, Author B. Template regression testing for journal manuscript formats. Journal Formatting Methods. 2026;1:1-10.")
    add_role("heading1", "Appendix")
    add_role("heading2", "Appendix Regression Checks")
    add_role("body", "The appendix verifies appendix heading behavior and numbering after the reference section.")

    output.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output))
    warnings = []
    if original_section_count > 1 and not transition_attached:
        warnings.append("Body normalization preserves the final section properties; intermediate section breaks require visual review.")
    return {
        "success": output.exists(),
        "output": str(output),
        "original_section_count": original_section_count,
        "inherited_page_furniture": inherited_page_furniture,
        "section_flow_preservation": {
            key: value for key, value in column_transition.items() if key != "sectPr"
        } | {"attached_after_role": "affiliation" if transition_attached else None},
        "style_roles": style_names,
        "direct_format_roles": [role for role, paragraph in direct_sources.items() if paragraph is not None],
        "direct_format_copy_decisions": direct_copy_decisions,
        "original_table_style": original_table_style,
        "warnings": warnings,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source")
    parser.add_argument("--output", required=True)
    parser.add_argument("--report", required=True)
    args = parser.parse_args()

    source = Path(args.source).expanduser().resolve()
    output = Path(args.output).expanduser().resolve()
    report_path = Path(args.report).expanduser().resolve()
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": str(source),
        "success": False,
        "normalization_mode": "same_manuscript_preserve_word_template_styles",
    }
    if not source.exists():
        report["error"] = "source not found"
    else:
        try:
            with tempfile.TemporaryDirectory(prefix="temp2tex-word-normalize-") as tmp:
                source_docx, conversion = convert_to_docx(source, Path(tmp))
                report["conversion"] = conversion
                if source_docx:
                    report.update(build_normalized_document(source_docx, output, output.parent / "figure-placeholder.png"))
        except Exception as exc:
            report["error"] = f"{type(exc).__name__}: {exc}"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(report_path)
    return 0 if report.get("success") else 1


if __name__ == "__main__":
    raise SystemExit(main())
