#!/usr/bin/env python3
"""Create a same-manuscript Word reference while preserving template formatting."""

from __future__ import annotations

import argparse
import copy
import json
import shutil
import subprocess
import tempfile
import zipfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Inches


W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
WP_NS = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
A_NS = "http://schemas.openxmlformats.org/drawingml/2006/main"
V_NS = "urn:schemas-microsoft-com:vml"


TITLE = "Temp2TeX Regression Benchmark: Template Fidelity Across Journal Formats"
ABSTRACT = (
    "This benchmark manuscript is intentionally structured to exercise journal template behavior. "
    "It contains front matter, author notes, an abstract, keywords, multiple heading levels, equations, "
    "tables, figures, footnotes, references, declarations, and an appendix. The same body is rendered "
    "through the official Word template and the LaTeX package generated by Temp2TeX from the official Word template."
)
KEYWORDS = "template conversion; LaTeX; Word template; regression testing; journal formatting"
SECTIONS = [
    (
        "Introduction",
        "The regression body verifies whether a converted template preserves the visual contract that a journal author expects from the official source. The body includes paragraphs with citations, inline mathematical symbols, emphasized terms, and cross references. A short footnote appears here to check footnote placement and numbering.",
    ),
    (
        "Methods",
        "The method section includes an equation and explanatory text. Equation (1) should appear with the journal's equation spacing and numbering policy.",
    ),
    (
        "Tables and Figures",
        "Table 1 checks caption placement, table rules, notes, alignment, and merged-cell behavior.",
    ),
    (
        "Results",
        "The result text cites the regression table, the single-panel figure, the paired-panel figure, and the displayed equation. The paragraph is long enough to wrap across multiple lines so the comparison can observe line spacing and text block width. It also contains a parenthetical citation placeholder (Author et al., 2026).",
    ),
    (
        "Discussion",
        "Discussion text checks body spacing after floats and headings. The converted template should keep the same page frame, header and footer behavior, caption style, and reference placement as the official LaTeX template when both templates receive this same manuscript body.",
    ),
    (
        "Conclusion",
        "This fixed body is not a scientific article. It is a deterministic template stress test for regression comparison.",
    ),
]

SECOND_LEVEL_TEXT = (
    "This section checks heading hierarchy, vertical spacing, paragraph indentation, and line width. "
    "It also verifies that a journal template can render normal body text without relying on example-specific macros."
)
THIRD_LEVEL_TEXT = (
    "Third-level headings are included because many official Word templates define them even when their LaTeX templates use a different command style."
)
RESULTS_TEXT = (
    "The result text cites Table 1, Figure 1, Figure 2, and Equation 1. The paragraph is long enough to wrap across multiple lines so that the comparison can observe line spacing and text block width. It also includes a parenthetical citation placeholder in plain text (Author et al., 2026)."
)
EQUATION_TEXT = "I = (sum from i=1 to n of w_i x_i) / (sum from i=1 to n of w_i)"

# Keep Chinese regression bodies language-consistent. These strings are
# verification fixtures, not reconstructed manuscript content.
CJK_TITLE = "中文期刊模板回归验证稿"
CJK_ABSTRACT = "摘要：本验证稿用于检查中文期刊模板的题名、作者、摘要、关键词、标题层级、图表、公式、脚注、参考文献和附录版式。"
CJK_KEYWORDS = "关键词：期刊模板；LaTeX；Word；版式验证"
CJK_SECTIONS = [
    ("模板验证样稿", "本段用于检查正文、首行缩进、行距、引文和交叉引用。文本长度足以发生换行，从而观察中文正文的宽度与段落密度。"),
    ("方法", "本节包含公式及其说明，用于检查公式上下间距和编号位置。"),
    ("公式、表格与图片", "表 1 用于检查题注位置、表格线、表注、对齐和单元格结构。"),
    ("结果", "结果段落用于检查图表与公式引用、图文间距及正文续排。"),
    ("讨论", "讨论段落用于检查标题后的正文间距、浮动体后的续排，以及页眉页脚和页边距的保持。"),
    ("结论", "此固定验证稿不是学术论文，用于比较 Word 模板与生成 LaTeX 模板的版式行为。"),
]
CJK_SECOND_LEVEL_TEXT = "本节检查二级标题间距、段落缩进和正文行宽。"
CJK_THIRD_LEVEL_TEXT = "本节检查三级标题格式。"
CJK_RESULTS_TEXT = "参见表 1、图 1、图 2 与公式 (1)。该段落用于检查长文本换行、图表引用和中文标点的排版行为。"

# This profile mirrors the editable CJK fixture emitted by
# generate_latex_package.py. It is deliberately separate from the broader
# stress fixture above: PDF comparison must not mistake content changes for
# template-layout differences.
CJK_LATEX_DEFAULT = {
    "title": "中文论文标题",
    "author": "第一作者；第二作者",
    "affiliation_1": "模板工程系，示例大学",
    "affiliation_2": "可复现排版学院，示例研究院",
    "abstract": "摘要：请在此填写中文摘要；如期刊要求双语摘要，请在中文摘要后添加英文摘要。",
    "keywords": "关键词：关键词一；关键词二；关键词三",
    "english_title": "English Title of the Manuscript",
    "english_author": "First Author; Second Author",
    "english_affiliation": "Department of Template Engineering, Example University",
    "english_abstract": "Abstract: Replace with the English abstract when the official template requires bilingual abstracts.",
    "english_keywords": "Keywords: keyword one; keyword two; keyword three",
    "intro": "此可编辑样稿用于检查正文、缩进、引文和交叉引用。其中包含一个脚注",
    "footnote": "示例脚注。",
    "second_check": "检查二级标题的间距。",
    "third_check": "检查三级标题的格式。",
    "result": "参见表 1、图 1 与公式 (1)；引用 [1]。",
    "reference": "[1] Author A. Sample reference placeholder. Journal Name. 2026;1(1):1-10.",
    "appendix_title": "A 附录验证样稿",
    "appendix_intro": "官方源文件未提供附录证据，此可编辑样稿用于验证附录计数器。",
}


def fixture_anchor_contract(
    fixture_language: str,
    fixture_profile: str,
    *,
    full_document_ready: bool = True,
    limitation: str | None = None,
) -> dict:
    """Return the explicit same-content contract for a generated fixture.

    The PDF profiler must never assume that a Chinese or bilingual fixture uses
    the English stress-body phrases. These are deliberately short, unique
    strings that occur in both render paths; they are verification metadata,
    not inferred journal rules.
    """
    fixture_language = str(fixture_language or "en").lower()
    fixture_profile = str(fixture_profile or "stress").lower()
    if fixture_language in {"zh", "mixed"} and fixture_profile == "latex-default":
        anchors = {
            "title": ["中文论文标题"],
            "abstract_zh": ["请在此填写中文摘要"],
            "keywords_zh": ["关键词一"],
            "title_en": ["English Title of the Manuscript"],
            "abstract_en": ["Replace with the English abstract"],
            "introduction": ["此可编辑样稿用于检查正文"],
            "heading_level_two": ["检查二级标题的间距"],
            "table_caption": ["带表注的示例表"],
            "table_note": ["示例表注"],
            "figure_caption": ["示例图片占位符"],
            "results": ["参见表 1、图 1"],
            "references": ["Sample reference placeholder"],
            "appendix": ["官方源文件未提供附录证据"],
        }
        if not full_document_ready:
            anchors = {
                name: anchors[name]
                for name in (
                    "title", "abstract_zh", "keywords_zh", "title_en",
                    "abstract_en", "introduction", "heading_level_two",
                )
            }
        return {
            "version": "fixture-anchor-cjk-latex-default-v2",
            "scope": "full_document" if full_document_ready else "partial_zone",
            "fixture_language": fixture_language,
            "fixture_profile": fixture_profile,
            "comparison_limitations": [] if full_document_ready else [
                limitation or "The Word source has no observable table or body-artwork object; injected default floats cannot calibrate the whole class."
            ],
            "anchors": anchors,
        }
    anchors = {
        "title": ["Temp2TeX Regression", "Template Fidelity"],
        "abstract": ["This benchmark", "template behavior"],
        "keywords": ["template conversion", "regression testing"],
        "introduction": ["The regression body verifies", "converted template preserves"],
        "methods": ["The method section includes", "Equation (1) should"],
        "table": ["Expected stress", "merged-cell behavior"],
        "figure": ["Single-panel figure", "subfigure regression"],
        "acknowledgements": ["The authors thank the template maintainers"],
        "data_availability": ["All data in this manuscript are placeholders"],
        "references": ["Template regression testing", "Journal Formatting Methods"],
        "appendix": ["Appendix Regression Checks", "appendix verifies"],
    }
    if not full_document_ready:
        anchors = {
            name: anchors[name]
            for name in ("title", "abstract", "keywords", "introduction", "methods")
        }
    return {
        "version": "fixture-anchor-en-stress-v2",
        "scope": "full_document" if full_document_ready else "partial_zone",
        "fixture_language": fixture_language,
        "fixture_profile": fixture_profile,
        "comparison_limitations": [] if full_document_ready else [
            limitation or "The Word source has no observable table or body-artwork object; injected default floats cannot calibrate the whole class."
        ],
        "anchors": anchors,
    }


def normalize_name(value: str) -> str:
    return " ".join(value.lower().replace("_", " ").replace("-", " ").split())


def paragraph_styles(doc: Document) -> list:
    return [style for style in doc.styles if style.type == WD_STYLE_TYPE.PARAGRAPH]


def style_by_terms(
    doc: Document,
    terms: list[str],
    excluded: tuple[str, ...] = (),
    prefer_used: bool = True,
):
    scored = []
    usage = style_usage(doc) if prefer_used else Counter()
    for style in paragraph_styles(doc):
        name = normalize_name(style.name)
        if any(term in name for term in excluded):
            continue
        score = 0
        for index, term in enumerate(terms):
            if name == term:
                score = max(score, 9000 - index * 1000)
            elif term in name:
                score = max(score, 8000 - index * 1000)
        if score:
            scored.append((score, bool(usage[style.style_id]), style))
    if prefer_used and any(item[1] for item in scored):
        scored = [item for item in scored if item[1]]
    return max(scored, key=lambda item: item[0])[2] if scored else None


def style_from_text(doc: Document, prefixes: tuple[str, ...]):
    for paragraph in doc.paragraphs:
        text = paragraph.text.strip().lower()
        if text.startswith(prefixes) and paragraph.style:
            return paragraph.style
    return None


def infer_body_style(doc: Document, excluded_ids: set[str]):
    counts: Counter[str] = Counter()
    styles = {}
    for paragraph in doc.paragraphs:
        text = paragraph.text.strip()
        style = paragraph.style
        if len(text) < 80 or not style or style.style_id in excluded_ids:
            continue
        # Template instructions often contain many long bibliography entries.
        # Exclude semantic non-body styles before choosing the most common
        # paragraph style, otherwise the regression manuscript is normalized
        # with a reference or caption style instead of the article body style.
        name = normalize_name(style.name)
        if any(term in name for term in (
            "reference", "bibliograph", "bib entry", "bibentry", "citation",
            "caption", "footnote", "endnote", "list", "table", "figure",
            "algorithm", "header", "footer", "acknowledg", "author", "affiliation",
            "abstract", "keyword", "title", "heading", "head ", "appendix",
        )):
            continue
        counts[style.style_id] += 1
        styles[style.style_id] = style
    if counts:
        return styles[counts.most_common(1)[0][0]]
    return style_by_terms(doc, ["body text", "body", "normal"])


def style_usage(doc: Document) -> Counter[str]:
    return Counter(
        paragraph.style.style_id
        for paragraph in doc.paragraphs
        if paragraph.text.strip() and paragraph.style is not None
    )


def infer_styles(doc: Document) -> dict[str, object]:
    title = style_by_terms(doc, ["article title", "manuscript title", "title"], ("subtitle", "running"))
    author = style_by_terms(doc, ["authors", "author"])
    affiliation = style_by_terms(doc, ["affiliations", "affiliation", "address", "institution"])
    abstract = style_by_terms(doc, ["abstract"]) or style_from_text(doc, ("abstract",))
    keywords = style_by_terms(doc, ["keywords", "key words"]) or style_from_text(doc, ("keywords", "key words"))
    heading1 = style_by_terms(doc, ["heading 1", "heading1", "head 1", "head1", "section heading", "main text", "section"], ("reference", "supporting"))
    heading2 = style_by_terms(doc, ["heading 2", "heading2", "head 2", "head2", "subsection"])
    heading3 = style_by_terms(doc, ["heading 3", "heading3", "head 3", "head3", "subsubsection"])
    caption = style_by_terms(doc, ["figure caption", "table caption", "caption"])
    reference = style_by_terms(doc, ["reference item", "references", "bibliography", "bib entry", "bibentry"])
    footnote = style_by_terms(doc, ["footnote text", "footnote"])
    excluded = {
        style.style_id
        for style in (title, author, affiliation, abstract, keywords, heading1, heading2, heading3, caption, reference)
        if style is not None
    }
    normal = style_by_terms(doc, ["normal"]) or next(iter(paragraph_styles(doc)), None)
    usage = style_usage(doc)
    named_body = style_by_terms(doc, ["main text", "body text", "article body", "journal body"])
    body = named_body if named_body is not None and usage[named_body.style_id] else infer_body_style(doc, excluded)
    if body is not None and normalize_name(body.name) in {"list", "list paragraph"}:
        body = normal
    roles = {
        "title": title or normal,
        "author": author or normal,
        "affiliation": affiliation or author or normal,
        "abstract": abstract or body or normal,
        "keywords": keywords or abstract or body or normal,
        "heading1": heading1 or normal,
        "heading2": heading2 or heading1 or normal,
        "heading3": heading3 or heading2 or heading1 or normal,
        "body": body or normal,
        "caption": caption or body or normal,
        "reference": reference or body or normal,
        "footnote": footnote or body or normal,
    }
    return roles


def find_soffice() -> str | None:
    candidates = [
        shutil.which("soffice"),
        shutil.which("soffice.exe"),
        r"D:\LibreOffice\program\soffice.exe",
    ]
    return next((item for item in candidates if item and Path(item).exists()), None)


def is_plain_docx_document(source: Path) -> bool:
    """Only bypass conversion for a package python-docx can open as a document."""
    if source.suffix.lower() != ".docx" or not zipfile.is_zipfile(source):
        return False
    try:
        with zipfile.ZipFile(source) as archive:
            content_types = archive.read("[Content_Types].xml")
        return b"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml" in content_types
    except (KeyError, OSError, zipfile.BadZipFile):
        return False


def convert_to_docx(source: Path, workdir: Path) -> tuple[Path | None, dict]:
    if is_plain_docx_document(source):
        return source, {"needed": False, "success": True, "source": str(source)}
    soffice = find_soffice()
    report = {"needed": True, "success": False, "source": str(source), "soffice": soffice}
    if not soffice:
        report["error"] = "LibreOffice is required to normalize legacy DOC/DOT/RTF or DOTX input"
        return None, report
    proc = subprocess.run(
        [soffice, "--headless", "--convert-to", "docx", "--outdir", str(workdir), str(source)],
        text=True,
        capture_output=True,
        timeout=45,
    )
    candidates = sorted(workdir.glob("*.docx"), key=lambda path: path.stat().st_mtime, reverse=True)
    report.update(
        {
            "returncode": proc.returncode,
            "stdout_tail": proc.stdout[-2000:],
            "stderr_tail": proc.stderr[-2000:],
            "success": bool(proc.returncode == 0 and candidates),
        }
    )
    if not report["success"]:
        report["error"] = "LibreOffice did not produce a DOCX normalization source"
        return None, report
    report["converted_docx"] = str(candidates[0])
    return candidates[0], report


def clear_body(doc: Document) -> None:
    body = doc._element.body
    for child in list(body):
        if child.tag.endswith("}sectPr"):
            continue
        body.remove(child)


def materialize_inherited_page_furniture(doc: Document) -> dict:
    """Make the final section's inherited header/footer references explicit."""
    sections = list(doc._element.body.xpath(".//w:sectPr"))
    if not sections:
        return {"section_count": 0, "materialized": []}

    active: dict[tuple[str, str], object] = {}
    for section in sections:
        for kind in ("headerReference", "footerReference"):
            for reference in section.findall(qn(f"w:{kind}")):
                variant = reference.get(qn("w:type")) or "default"
                active[(kind, variant)] = reference

    final_section = sections[-1]
    explicit = {
        (kind, reference.get(qn("w:type")) or "default")
        for kind in ("headerReference", "footerReference")
        for reference in final_section.findall(qn(f"w:{kind}"))
    }
    materialized = []
    for (kind, variant), reference in active.items():
        if (kind, variant) in explicit:
            continue
        copied = copy.deepcopy(reference)
        # Header/footer references must precede the page geometry children in
        # sectPr. Insert after any existing reference nodes.
        insert_at = 0
        for index, child in enumerate(final_section):
            local = child.tag.split("}")[-1]
            if local in {"headerReference", "footerReference"}:
                insert_at = index + 1
        final_section.insert(insert_at, copied)
        materialized.append(
            {
                "kind": "header" if kind == "headerReference" else "footer",
                "variant": variant,
                "relationship_id": copied.get(qn("r:id")),
                "source": "inherited from the latest preceding Word section reference",
            }
        )
    return {"section_count": len(sections), "materialized": materialized}


def front_matter_column_transition(doc: Document) -> dict:
    """Capture the first explicit one-column to two-column section transition."""
    sections = list(doc._element.body.xpath(".//w:sectPr"))

    def column_count(section) -> int:
        columns = section.find(qn("w:cols"))
        if columns is None:
            return 1
        try:
            return max(1, int(columns.get(qn("w:num")) or "1"))
        except ValueError:
            return 1

    for index in range(len(sections) - 1):
        current = sections[index]
        following = sections[index + 1]
        break_node = current.find(qn("w:type"))
        break_type = break_node.get(qn("w:val")) if break_node is not None else "nextPage"
        if column_count(current) == 1 and column_count(following) == 2:
            return {
                "available": True,
                "source_section_index": index + 1,
                "following_section_index": index + 2,
                "break_type": break_type,
                "latex_mode": "continuous" if break_type == "continuous" else "new_page",
                "from_columns": 1,
                "to_columns": 2,
                "sectPr": copy.deepcopy(current),
            }
    return {"available": False}


def attach_section_break(paragraph, transition: dict) -> bool:
    section = transition.get("sectPr") if isinstance(transition, dict) else None
    if section is None:
        return False
    properties = paragraph._p.get_or_add_pPr()
    existing = properties.find(qn("w:sectPr"))
    if existing is not None:
        properties.remove(existing)
    properties.append(copy.deepcopy(section))
    return True


def copy_direct_paragraph_format(source, target) -> None:
    """Copy paragraph and baseline run properties from a direct-format source."""
    if source is None:
        return
    source_ppr = source._p.pPr
    if source_ppr is not None:
        target_ppr = target._p.pPr
        if target_ppr is not None:
            target._p.remove(target_ppr)
        target._p.insert(0, copy.deepcopy(source_ppr))
    if source.runs and target.runs and source.runs[0]._r.rPr is not None:
        target_run = target.runs[0]
        target_rpr = target_run._r.rPr
        if target_rpr is not None:
            target_run._r.remove(target_rpr)
        target_run._r.insert(0, copy.deepcopy(source.runs[0]._r.rPr))


def add_paragraph(doc: Document, text: str, style, source=None) -> object:
    paragraph = doc.add_paragraph(style=style)
    paragraph.add_run(text)
    copy_direct_paragraph_format(source, paragraph)
    return paragraph


def direct_role_samples(doc: Document) -> dict[str, object]:
    """Find visible role exemplars for templates that do not use Word styles."""
    paragraphs = [paragraph for paragraph in doc.paragraphs if paragraph.text.strip()]
    abstract_index = next(
        (
            index
            for index, paragraph in enumerate(paragraphs, 1)
            if paragraph.text.strip().lower().startswith(("abstract", "摘要", "中文摘要", "英文摘要"))
        ),
        None,
    )

    def first(predicate):
        return next((paragraph for index, paragraph in enumerate(paragraphs, 1) if predicate(paragraph.text.strip(), index)), None)

    affiliation_markers = ("university", "college", "institute", "laboratory", "department", "\u5927\u5b66", "\u5b66\u9662", "\u7814\u7a76\u6240", "\u5b9e\u9a8c\u5ba4", "\u5355\u4f4d", "\u90ae\u7f16")
    def is_affiliation(text: str) -> bool:
        return any(marker in text.lower() for marker in affiliation_markers)
    def heading_level(text: str, index: int):
        # Chinese templates often number affiliations before the abstract.
        # Those lines are front matter, never body heading exemplars.
        if abstract_index is not None and index < abstract_index:
            return None
        import re
        match = re.match(r"^(\d+)(?:\.(\d+))?(?:\.(\d+))?[.)]?\s+\S+", text)
        if not match or is_affiliation(text):
            return None
        return 2 if match.group(3) else 1 if match.group(2) else 0

    title = first(lambda text, index: index <= 3 and len(text) >= 6)
    abstract = first(lambda text, index: text.lower().startswith("abstract") or text.startswith("\u6458\u8981"))
    keywords = first(lambda text, index: text.lower().startswith(("keyword", "key word")) or text.startswith("\u5173\u952e\u8bcd"))
    author = first(lambda text, index: index <= 8 and ("," in text or "\uff0c" in text) and not text.startswith(("\u6458\u8981", "\u5173\u952e\u8bcd")))
    affiliation = first(lambda text, index: index <= 16 and is_affiliation(text))
    body_candidates = [
        paragraph
        for index, paragraph in enumerate(paragraphs, 1)
        if (abstract_index is None or index > abstract_index)
        and len(paragraph.text.strip()) >= 80
        and not paragraph.text.strip().lower().startswith(("abstract", "摘要", "关键词", "key words", "keywords"))
    ]
    body = max(body_candidates, key=lambda item: len(item.text), default=None)
    headings = {level: first(lambda text, index, level=level: heading_level(text, index) == level) for level in range(3)}
    reference = first(lambda text, index: text.lower() == "references" or text.startswith("\u53c2\u8003\u6587\u732e"))
    return {
        "title": title,
        "author": author,
        "affiliation": affiliation,
        "abstract": abstract,
        "keywords": keywords,
        "heading1": headings[0],
        "heading2": headings[1] or headings[0],
        "heading3": headings[2] or headings[1] or headings[0],
        "body": body,
        "caption": body,
        "reference": reference or body,
        "footnote": body,
    }


def add_placeholder_figure(
    doc: Document,
    path: Path,
    style,
    *,
    paired: bool = False,
    caption: str | None = None,
    label: str | None = None,
    label_separator: str = ". ",
    width_inches: float | None = None,
    height_inches: float | None = None,
) -> None:
    fixture_sizes = getattr(doc, "_temp2tex_fixture_figure_sizes", {})
    fixture_size = fixture_sizes.get(path.name) if isinstance(fixture_sizes, dict) else None
    if fixture_size and width_inches is None:
        width_inches = fixture_size[0]
    if fixture_size and height_inches is None:
        height_inches = fixture_size[1]
    try:
        from PIL import Image, ImageDraw

        path.parent.mkdir(parents=True, exist_ok=True)
        image = Image.new("RGB", (1200, 480), "white")
        draw = ImageDraw.Draw(image)
        if paired:
            draw.rectangle((8, 8, 571, 471), outline="black", width=6)
            draw.rectangle((629, 8, 1191, 471), outline="black", width=6)
            draw.text((175, 210), "Panel A", fill="black")
            draw.text((795, 210), "Panel B", fill="black")
        else:
            draw.rectangle((8, 8, 1191, 471), outline="black", width=6)
            draw.text((70, 210), "Temp2TeX regression figure placeholder", fill="black")
        image.save(path)
        paragraph = doc.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        picture_kwargs = {"width": Inches(width_inches if width_inches is not None else 4.7)}
        if height_inches is not None:
            picture_kwargs["height"] = Inches(height_inches)
        paragraph.add_run().add_picture(str(path), **picture_kwargs)
    except Exception:
        add_paragraph(doc, "[Temp2TeX regression figure placeholder]", style)
    caption = caption or ("Two-panel figure placeholder used for subfigure regression" if paired else "Single-panel figure placeholder used for layout regression")
    caption_label = label or ("图" if caption.startswith("示例") else "Figure")
    number = "" if label else f" {'2' if paired else '1'}"
    add_paragraph(doc, f"{caption_label}{number}{label_separator}{caption}", style)


def source_body_object_evidence(doc: Document) -> dict:
    """Count source objects without mistaking anchored artwork for absent evidence.

    ``python-docx`` exposes only inline shapes.  Word templates often keep
    figures as DrawingML anchors, while VML image fallbacks occur in older
    files.  Count only image-bearing drawing containers here: a text box,
    rule, or other non-image decoration is not evidence for the generic figure
    fixture used in a full-document PDF comparison.
    """
    body = doc.element.body
    table_tag = f"{{{W_NS}}}tbl"
    inline_tag = f"{{{WP_NS}}}inline"
    anchor_tag = f"{{{WP_NS}}}anchor"
    blip_tag = f"{{{A_NS}}}blip"
    vml_image_tag = f"{{{V_NS}}}imagedata"
    tables = sum(1 for node in body.iter() if node.tag == table_tag)
    inline_images = 0
    anchored_images = 0
    for node in body.iter():
        if node.tag not in {inline_tag, anchor_tag}:
            continue
        if any(child.tag == blip_tag for child in node.iter()):
            if node.tag == inline_tag:
                inline_images += 1
            else:
                anchored_images += 1
    vml_images = sum(1 for node in body.iter() if node.tag == vml_image_tag)
    figure_count = inline_images + anchored_images + vml_images
    return {
        "table_count": tables,
        "inline_image_count": inline_images,
        "anchored_image_count": anchored_images,
        "vml_image_count": vml_images,
        "figure_object_count": figure_count,
        "full_document_comparison_ready": bool(tables and figure_count),
        "rule": "A full-document fixture contract needs observable Word evidence for both tables and body image objects, or an independently verified shared structural fixture.",
    }


def build_normalized_document(
    source_docx: Path,
    output: Path,
    figure_path: Path,
    fixture_language: str = "en",
    fixture_profile: str = "stress",
) -> dict:
    doc = Document(str(source_docx))
    source_objects = source_body_object_evidence(doc)
    is_cjk = fixture_language in {"zh", "mixed"}
    latex_default_cjk = is_cjk and fixture_profile == "latex-default"
    title = CJK_LATEX_DEFAULT["title"] if latex_default_cjk else (CJK_TITLE if is_cjk else TITLE)
    abstract = CJK_LATEX_DEFAULT["abstract"] if latex_default_cjk else (CJK_ABSTRACT if is_cjk else f"Abstract: {ABSTRACT}")
    keywords = CJK_LATEX_DEFAULT["keywords"] if latex_default_cjk else (CJK_KEYWORDS if is_cjk else f"Keywords: {KEYWORDS}")
    sections = CJK_SECTIONS if is_cjk else SECTIONS
    second_level_text = CJK_SECOND_LEVEL_TEXT if is_cjk else SECOND_LEVEL_TEXT
    third_level_text = CJK_THIRD_LEVEL_TEXT if is_cjk else THIRD_LEVEL_TEXT
    results_text = CJK_RESULTS_TEXT if is_cjk else RESULTS_TEXT
    if latex_default_cjk:
        sections = [
            ("1 模板验证样稿", CJK_LATEX_DEFAULT["intro"]),
            ("2 公式、表格与图片", ""),
            ("3 结果", CJK_LATEX_DEFAULT["result"]),
        ]
        second_level_text = CJK_LATEX_DEFAULT["second_check"]
        third_level_text = CJK_LATEX_DEFAULT["third_check"]
        results_text = CJK_LATEX_DEFAULT["result"]
    intro_heading = "1 模板验证样稿" if latex_default_cjk else ("模板验证样稿" if is_cjk else "Introduction")
    tables_heading = "2 公式、表格与图片" if latex_default_cjk else ("公式、表格与图片" if is_cjk else "Tables and Figures")
    methods_heading = "方法" if is_cjk else "Methods"
    results_heading = "3 结果" if latex_default_cjk else ("结果" if is_cjk else "Results")
    cjk_primary_figure_size = None
    cjk_appendix_figure_size = None
    if latex_default_cjk and doc.sections:
        # Match the generated editable CJK fixture: a full text-width 35 mm
        # primary frame and a 45%-width 12 mm appendix frame. These are
        # fixture geometry, not inferred journal artwork requirements.
        section = doc.sections[0]
        body_width_inches = (
            section.page_width - section.left_margin - section.right_margin
        ) / 914400
        cjk_primary_figure_size = (body_width_inches, 35 / 25.4)
        cjk_appendix_figure_size = (body_width_inches * 0.45, 12 / 25.4)
        doc._temp2tex_fixture_figure_sizes = {
            figure_path.name: cjk_primary_figure_size,
            "appendix-figure-placeholder.png": cjk_appendix_figure_size,
        }
    original_section_count = len(doc.sections)
    inherited_page_furniture = materialize_inherited_page_furniture(doc)
    column_transition = front_matter_column_transition(doc)
    original_table_style = None
    if doc.tables and doc.tables[0].style:
        original_table_style = doc.tables[0].style.name
    styles = infer_styles(doc)
    style_names = {role: style.name if style is not None else None for role, style in styles.items()}
    direct_sources = direct_role_samples(doc)
    visible_paragraphs = [paragraph for paragraph in doc.paragraphs if paragraph.text.strip()]

    def next_visible_paragraph(source):
        if source is None:
            return None
        for index, paragraph in enumerate(visible_paragraphs):
            if paragraph._p is source._p:
                return visible_paragraphs[index + 1] if index + 1 < len(visible_paragraphs) else None
        return None

    abstract_label_source = direct_sources.get("abstract")
    abstract_label_text = abstract_label_source.text.strip().rstrip(":：") if abstract_label_source is not None else ""
    abstract_is_separate_label = abstract_label_text.lower() in {"abstract", "摘要", "中文摘要", "英文摘要"}
    abstract_content_source = next_visible_paragraph(abstract_label_source) if abstract_is_separate_label else None
    if abstract_is_separate_label:
        for prefix in (f"{abstract_label_text}:", f"{abstract_label_text}："):
            if abstract.lower().startswith(prefix.lower()):
                abstract = abstract[len(prefix):].lstrip()
                break
    clear_body(doc)
    direct_copy_decisions: dict[str, str] = {}

    def add_role(role: str, text: str):
        source = direct_sources.get(role)
        target_style = styles[role]
        # Direct formatting may only be copied from the same Word style. A
        # long Abstract/instruction paragraph must not overwrite body text.
        if source is not None and target_style is not None and source.style is not None:
            if source.style.style_id != target_style.style_id:
                direct_copy_decisions[role] = "skipped_style_mismatch"
                source = None
            else:
                direct_copy_decisions[role] = "copied_same_style"
        elif source is not None:
            direct_copy_decisions[role] = "copied_no_style_guard"
        return add_paragraph(doc, text, target_style, source)

    add_role("title", title)
    author_text = CJK_LATEX_DEFAULT["author"] if latex_default_cjk else ("张三，李四" if is_cjk else "Alex Example and Blair Example")
    affiliation_text = CJK_LATEX_DEFAULT["affiliation_1"] if latex_default_cjk else ("模板工程系，示例大学，北京 100000" if is_cjk else "Department of Template Engineering, Example University; alex.example@example.org")
    affiliation_paragraph = add_role("author", author_text)
    affiliation_paragraph = add_role("affiliation", affiliation_text)
    if latex_default_cjk:
        affiliation_paragraph = add_role("affiliation", CJK_LATEX_DEFAULT["affiliation_2"])
    transition_attached = attach_section_break(affiliation_paragraph, column_transition)
    if abstract_is_separate_label and abstract_content_source is not None:
        # A standalone Word label and its following content paragraph carry
        # distinct run/paragraph formatting. Preserve that split in the fixed
        # regression manuscript instead of inheriting label boldness or
        # spacing across the abstract body.
        add_paragraph(doc, abstract_label_text, styles["abstract"], abstract_label_source)
        add_paragraph(doc, abstract, styles["abstract"], abstract_content_source)
    else:
        add_role("abstract", abstract)
    add_role("keywords", keywords)
    if fixture_language == "mixed":
        add_role("title", CJK_LATEX_DEFAULT["english_title"] if latex_default_cjk else "English Title of the Regression Manuscript")
        add_role("author", CJK_LATEX_DEFAULT["english_author"] if latex_default_cjk else "Zhang San; Li Si")
        add_role("affiliation", CJK_LATEX_DEFAULT["english_affiliation"] if latex_default_cjk else "Department of Template Engineering, Example University, Beijing 100000, China")
        add_role("abstract", CJK_LATEX_DEFAULT["english_abstract"] if latex_default_cjk else "Abstract: This regression fixture checks bilingual front matter and journal layout behavior.")
        add_role("keywords", CJK_LATEX_DEFAULT["english_keywords"] if latex_default_cjk else "Key words: journal template; LaTeX; Word; layout verification")

    for heading, text in sections:
        add_role("heading1", heading)
        paragraph = add_role("body", text)
        if heading == intro_heading:
            marker = paragraph.add_run("1")
            marker.font.superscript = True
            add_role("footnote", CJK_LATEX_DEFAULT["footnote"] if latex_default_cjk else ("1 此脚注属于固定中文回归样稿。" if is_cjk else "1 This footnote is part of the fixed regression body."))
        if heading == intro_heading:
            add_role("heading2", "1.1 二级标题" if latex_default_cjk else ("二级标题" if is_cjk else "Second-level heading"))
            add_role("body", second_level_text)
            add_role("heading3", "1.1.1 三级标题" if latex_default_cjk else ("三级标题" if is_cjk else "Third-level heading"))
            add_role("body", third_level_text)
            if latex_default_cjk:
                add_role("heading3", "四级标题")
                add_role("body", "行内文字。")
                add_role("heading3", "五级标题")
                add_role("body", "行内文字。")
        if heading == tables_heading:
            add_role("caption", "表 1: 带表注的示例表" if latex_default_cjk else ("表 1. 带表注的回归验证表" if is_cjk else "Table 1. Regression table with a note and a merged cell"))
            table = doc.add_table(rows=3 if latex_default_cjk else 4, cols=3)
            if original_table_style:
                try:
                    table.style = original_table_style
                except Exception:
                    pass
            values = (
                [("Column A", "Column B", "Column C"), ("Merged cells", "", "Value"), ("Item 1", "Item 2", "Item 3")]
                if latex_default_cjk
                else [
                    ("Format element", "Expected stress", "Evidence target"),
                    ("Merged-cell row", "", "table structure"),
                    ("Heading levels", "section to subsubsection", "text hierarchy"),
                    ("Figures", "single and paired panels", "caption layout"),
                ]
            )
            for row, values_row in zip(table.rows, values):
                for cell, value in zip(row.cells, values_row):
                    cell.text = value
            add_role("caption", "示例表注。" if latex_default_cjk else ("注：本表用于检查表注位置。" if is_cjk else "Note: the table intentionally includes a note below the tabular block."))
            if latex_default_cjk:
                add_role("body", "E = mc2")
            add_placeholder_figure(doc, figure_path, styles["caption"], caption="示例图片占位符" if latex_default_cjk else None, label_separator=": " if latex_default_cjk else ". ")
            if not latex_default_cjk:
                add_placeholder_figure(doc, figure_path.with_name("paired-figure-placeholder.png"), styles["caption"], paired=True)
        if heading == methods_heading:
            add_role("body", EQUATION_TEXT)
        if heading == results_heading:
            # Replace the generic section text with the same content ordering
            # used by the LaTeX stress body.
            paragraph.text = results_text
            paragraph.style = styles["body"]
    if not latex_default_cjk:
        add_role("heading1", "致谢" if is_cjk else "Acknowledgements")
        add_role("body", "感谢模板维护人员。本样稿不涉及外部经费。" if is_cjk else "The authors thank the template maintainers. No external funding was used.")
        add_role("heading1", "数据可用性" if is_cjk else "Data Availability")
        add_role("body", "本样稿中的数据均为模板回归验证占位内容。" if is_cjk else "All data in this manuscript are placeholders created for template regression testing.")
    add_role("heading1", "参考文献" if is_cjk else "References")
    add_role("reference", CJK_LATEX_DEFAULT["reference"] if latex_default_cjk else ("张三，李四. 中文期刊模板回归验证方法. 科技期刊排版. 2026, 1(1): 1-10." if is_cjk else "Author A, Author B. Template regression testing for journal manuscript formats. Journal Formatting Methods. 2026;1:1-10."))
    if latex_default_cjk:
        add_role("heading1", CJK_LATEX_DEFAULT["appendix_title"])
        add_role("body", CJK_LATEX_DEFAULT["appendix_intro"])
        add_role("body", "a + b = c (A.1)")
        add_role("caption", "表 A.1: 附录表格验证")
        appendix_table = doc.add_table(rows=2, cols=2)
        appendix_table.rows[0].cells[0].text = "项目"
        appendix_table.rows[0].cells[1].text = "值"
        appendix_table.rows[1].cells[0].text = "附录证据"
        appendix_table.rows[1].cells[1].text = "可编辑"
        add_placeholder_figure(
            doc,
            figure_path.with_name("appendix-figure-placeholder.png"),
            styles["caption"],
            caption="附录图片验证",
            label="图 A.1",
            label_separator=": ",
        )
    else:
        add_role("heading1", "附录" if is_cjk else "Appendix")
        add_role("heading2", "附录验证" if is_cjk else "Appendix Regression Checks")
        add_role("body", "附录用于验证参考文献后的附录标题和编号行为。" if is_cjk else "The appendix verifies appendix heading behavior and numbering after the reference section.")

    output.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output))
    warnings = []
    if original_section_count > 1 and not transition_attached:
        warnings.append("Body normalization preserves the final section properties; intermediate section breaks require visual review.")
    return {
        "success": output.exists(),
        "output": str(output),
        "fixture_language": fixture_language,
        "fixture_profile": fixture_profile,
        "original_section_count": original_section_count,
        "inherited_page_furniture": inherited_page_furniture,
        "section_flow_preservation": {
            key: value for key, value in column_transition.items() if key != "sectPr"
        } | {"attached_after_role": "affiliation" if transition_attached else None},
        "style_roles": style_names,
        "direct_format_roles": [role for role, paragraph in direct_sources.items() if paragraph is not None],
        "direct_format_copy_decisions": direct_copy_decisions,
        "original_table_style": original_table_style,
        "source_object_evidence": source_objects,
        "warnings": warnings,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source")
    parser.add_argument("--output", required=True)
    parser.add_argument("--report", required=True)
    parser.add_argument("--fixture-language", choices=["en", "zh", "mixed"], default="en")
    parser.add_argument("--fixture-profile", choices=["stress", "latex-default"], default="stress")
    parser.add_argument(
        "--anchors-output",
        help="Write the language- and profile-specific same-content anchor contract used for PDF comparison.",
    )
    args = parser.parse_args()

    source = Path(args.source).expanduser().resolve()
    output = Path(args.output).expanduser().resolve()
    report_path = Path(args.report).expanduser().resolve()
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": str(source),
        "success": False,
        "normalization_mode": "same_manuscript_preserve_word_template_styles",
    }
    if not source.exists():
        report["error"] = "source not found"
    else:
        try:
            with tempfile.TemporaryDirectory(prefix="temp2tex-word-normalize-") as tmp:
                source_docx, conversion = convert_to_docx(source, Path(tmp))
                report["conversion"] = conversion
                if source_docx:
                    report.update(build_normalized_document(source_docx, output, output.parent / "figure-placeholder.png", args.fixture_language, args.fixture_profile))
        except Exception as exc:
            report["error"] = f"{type(exc).__name__}: {exc}"
    if args.anchors_output:
        anchor_path = Path(args.anchors_output).expanduser().resolve()
        anchor_path.parent.mkdir(parents=True, exist_ok=True)
        source_objects = report.get("source_object_evidence", {})
        full_document_ready = bool(source_objects.get("full_document_comparison_ready"))
        limitation = None
        if not full_document_ready:
            limitation = (
                "The official Word source exposes {tables} table(s) and {figures} body image object(s) "
                "({inline} inline, {anchored} anchored, {vml} VML); "
                "the injected table/figure fixture is limited to local diagnostics until both render paths share a verified structural contract."
            ).format(
                tables=source_objects.get("table_count", 0),
                figures=source_objects.get("figure_object_count", 0),
                inline=source_objects.get("inline_image_count", 0),
                anchored=source_objects.get("anchored_image_count", 0),
                vml=source_objects.get("vml_image_count", 0),
            )
        contract = fixture_anchor_contract(
            args.fixture_language,
            args.fixture_profile,
            full_document_ready=full_document_ready,
            limitation=limitation,
        )
        anchor_path.write_text(json.dumps(contract, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        report["anchor_contract"] = {
            "path": str(anchor_path),
            "version": contract["version"],
            "scope": contract["scope"],
        }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(report_path)
    return 0 if report.get("success") else 1


if __name__ == "__main__":
    raise SystemExit(main())
